// MCP-311 (ADR-119, Batch D) — runtime IDL drift assertion for vault-layout.
//
// `vault-layout.generated.ts` is committed and re-generated by
// `scripts/gen-vault-layout.ts` at build time. CI verifies
// `git diff --exit-code` post-codegen so a Rust struct reorder fails the
// build. This module adds a runtime defense-in-depth: at boot, re-walk
// the live IDL and assert the offsets in the generated file STILL match.
// Catches the case where the operator deployed a stale generated artifact
// against a newer IDL (e.g. published mcp-server tarball vs. fresh
// programs/agent-vault binary).

import * as fs from "node:fs";
import * as path from "node:path";

import {
  SPENT_TODAY_OFFSET,
  LAST_SPEND_DAY_OFFSET,
  POLICY_PER_TX_LIMIT_OFFSET,
  DAILY_LIMIT_OFFSET,
  POLICY_FIXED_END_OFFSET,
  TOKEN_SPEND_RECORD_SIZE,
  VAULT_PREFIX_FIELDS,
} from "./vault-layout.generated.js";
import { serverLogger } from "../util/logger.js";

const log = serverLogger.child({ component: "vault-layout-drift" });

// ---------------------------------------------------------------------------
// Anchor primitive sizes (mirror of `scripts/gen-vault-layout.ts`)
// ---------------------------------------------------------------------------

const PRIMITIVE_SIZES: Record<string, number> = {
  bool: 1,
  u8: 1, i8: 1,
  u16: 2, i16: 2,
  u32: 4, i32: 4,
  u64: 8, i64: 8,
  u128: 16, i128: 16,
  f32: 4, f64: 8,
  pubkey: 32, publicKey: 32,
};

interface IdlField { name: string; type: unknown }
interface IdlStructType { kind: "struct"; fields: IdlField[] }
interface IdlType { name: string; type: IdlStructType | { kind: string } }
interface IdlAccount { name: string; type?: IdlStructType }
interface Idl { accounts?: IdlAccount[]; types?: IdlType[] }

class VariableWidth extends Error {}

function fieldSize(idl: Idl, t: unknown, p: string): number {
  if (typeof t === "string") {
    if (t in PRIMITIVE_SIZES) return PRIMITIVE_SIZES[t]!;
    throw new Error(`unknown primitive at ${p}: ${t}`);
  }
  if (t && typeof t === "object") {
    const o = t as Record<string, unknown>;
    if ("vec" in o || "option" in o || "string" in o) throw new VariableWidth();
    if ("array" in o && Array.isArray(o.array)) {
      const [el, len] = o.array as [unknown, number];
      return fieldSize(idl, el, `${p}[*]`) * len;
    }
    if ("defined" in o) {
      const def = o.defined as { name?: string } | string;
      const refName = typeof def === "string" ? def : def.name;
      if (!refName) throw new Error(`malformed defined at ${p}`);
      const ref = (idl.types ?? []).find((x) => x.name === refName);
      if (!ref || ref.type.kind !== "struct") throw new Error(`unknown ${refName}`);
      let s = 0;
      for (const f of (ref.type as IdlStructType).fields) {
        s += fieldSize(idl, f.type, `${p}.${f.name}`);
      }
      return s;
    }
  }
  throw new Error(`unsupported type at ${p}`);
}

interface PrefixField { name: string; offset: number; size: number }

function walkField(
  idl: Idl,
  pathPrefix: string,
  fieldName: string,
  fieldType: unknown,
  cursor: number,
  out: PrefixField[],
): { cursor: number; stopped: boolean } {
  if (fieldType && typeof fieldType === "object") {
    const obj = fieldType as Record<string, unknown>;
    if ("vec" in obj || "option" in obj || "string" in obj) {
      return { cursor, stopped: true };
    }
    if ("array" in obj && Array.isArray(obj.array)) {
      const [elemType, len] = obj.array as [unknown, number];
      const total = fieldSize(idl, elemType, `${pathPrefix}${fieldName}[*]`) * len;
      out.push({ name: `${pathPrefix}${fieldName}`, offset: cursor, size: total });
      return { cursor: cursor + total, stopped: false };
    }
    if ("defined" in obj) {
      const def = obj.defined as { name?: string } | string;
      const refName = typeof def === "string" ? def : def.name;
      if (!refName) throw new Error("malformed defined ref");
      const ref = (idl.types ?? []).find((t) => t.name === refName);
      if (!ref) throw new Error(`unknown defined: ${refName}`);
      if (ref.type.kind !== "struct") return { cursor, stopped: true };
      const startCursor = cursor;
      let inner = cursor;
      let stopped = false;
      out.push({ name: `${pathPrefix}${fieldName}`, offset: startCursor, size: 0 });
      const next = `${pathPrefix}${fieldName}.`;
      for (const sf of (ref.type as IdlStructType).fields) {
        const r = walkField(idl, next, sf.name, sf.type, inner, out);
        inner = r.cursor;
        if (r.stopped) {
          stopped = true;
          break;
        }
      }
      const parent = out.find(
        (f) => f.name === `${pathPrefix}${fieldName}` && f.size === 0,
      );
      if (parent) parent.size = inner - startCursor;
      return { cursor: inner, stopped };
    }
  }
  const size = fieldSize(idl, fieldType, `${pathPrefix}${fieldName}`);
  out.push({ name: `${pathPrefix}${fieldName}`, offset: cursor, size });
  return { cursor: cursor + size, stopped: false };
}

function walkPrefix(idl: Idl, accountName: string): PrefixField[] {
  const account = (idl.accounts ?? []).find((a) => a.name === accountName);
  let struct: IdlStructType | undefined;
  if (account?.type && account.type.kind === "struct") {
    struct = account.type as IdlStructType;
  } else {
    const t = (idl.types ?? []).find((tt) => tt.name === accountName);
    if (t && t.type.kind === "struct") struct = t.type as IdlStructType;
  }
  if (!struct) throw new Error(`account ${accountName} has no struct type`);
  const out: PrefixField[] = [];
  let cursor = 8; // discriminator
  for (const f of struct.fields) {
    const r = walkField(idl, "", f.name, f.type, cursor, out);
    cursor = r.cursor;
    if (r.stopped) break;
  }
  return out;
}

function tokenSpendRecordSize(idl: Idl): number {
  const t = (idl.types ?? []).find((tt) => tt.name === "TokenSpendRecord");
  if (!t || t.type.kind !== "struct") throw new Error("TokenSpendRecord missing");
  let s = 0;
  for (const f of (t.type as IdlStructType).fields) {
    s += fieldSize(idl, f.type, `TokenSpendRecord.${f.name}`);
  }
  return s;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export class VaultLayoutDriftError extends Error {
  constructor(public readonly diffs: string[]) {
    super(
      `vault-layout drift detected: generated artifact does not match live IDL.\n` +
        diffs.map((d) => `  - ${d}`).join("\n") +
        `\n\nRun \`npm run gen:vault-layout\` and rebuild.`,
    );
    this.name = "VaultLayoutDriftError";
  }
}

export interface VaultLayoutDriftCheckOptions {
  /** Override the IDL path. Defaults to `<repoRoot>/sdk/idl/src/idl/agent_vault.json`. */
  idlPath?: string;
  /** Inject the IDL JSON directly (used by tests to avoid filesystem). */
  idlJson?: unknown;
}

/**
 * Re-walks the live IDL and asserts every constant in the generated module
 * still matches. Throws `VaultLayoutDriftError` on the first mismatch, with
 * a multi-line diff describing every divergence.
 *
 * Called once at boot from `index.ts` (best-effort; if the IDL file is not
 * present in the runtime image, drift can only be checked at build time).
 */
export function assertVaultLayoutMatchesIdl(
  options: VaultLayoutDriftCheckOptions = {},
): void {
  let idl: Idl;
  if (options.idlJson !== undefined) {
    idl = options.idlJson as Idl;
  } else {
    const idlPath =
      options.idlPath ??
      path.resolve(process.cwd(), "sdk/idl/src/idl/agent_vault.json");
    if (!fs.existsSync(idlPath)) {
      log.warn(
        { idl_path: idlPath, audit: "MCP-311" },
        "vault-layout-drift: IDL not present at runtime; skipping drift check (build-time gate is authoritative)",
      );
      return;
    }
    idl = JSON.parse(fs.readFileSync(idlPath, "utf8")) as Idl;
  }

  const liveFields = walkPrefix(idl, "Vault");
  const liveTokenRecordSize = tokenSpendRecordSize(idl);

  const diffs: string[] = [];

  // Compare each generated constant against the live walk.
  const expected: Record<string, number> = {};
  for (const f of liveFields) expected[f.name] = f.offset;

  if (expected["spent_today_lamports"] !== SPENT_TODAY_OFFSET) {
    diffs.push(
      `SPENT_TODAY_OFFSET: generated=${SPENT_TODAY_OFFSET}, live=${expected["spent_today_lamports"]}`,
    );
  }
  if (expected["last_spend_day"] !== LAST_SPEND_DAY_OFFSET) {
    diffs.push(
      `LAST_SPEND_DAY_OFFSET: generated=${LAST_SPEND_DAY_OFFSET}, live=${expected["last_spend_day"]}`,
    );
  }
  if (expected["policy.per_tx_limit_lamports"] !== POLICY_PER_TX_LIMIT_OFFSET) {
    diffs.push(
      `POLICY_PER_TX_LIMIT_OFFSET: generated=${POLICY_PER_TX_LIMIT_OFFSET}, live=${expected["policy.per_tx_limit_lamports"]}`,
    );
  }
  if (expected["policy.daily_limit_lamports"] !== DAILY_LIMIT_OFFSET) {
    diffs.push(
      `DAILY_LIMIT_OFFSET: generated=${DAILY_LIMIT_OFFSET}, live=${expected["policy.daily_limit_lamports"]}`,
    );
  }
  // POLICY_FIXED_END_OFFSET = end of policy.max_txs_per_hour
  const liveMaxTxs = liveFields.find((f) => f.name === "policy.max_txs_per_hour");
  if (liveMaxTxs) {
    const livePolicyEnd = liveMaxTxs.offset + liveMaxTxs.size;
    if (livePolicyEnd !== POLICY_FIXED_END_OFFSET) {
      diffs.push(
        `POLICY_FIXED_END_OFFSET: generated=${POLICY_FIXED_END_OFFSET}, live=${livePolicyEnd}`,
      );
    }
  } else {
    diffs.push("POLICY_FIXED_END_OFFSET: live IDL missing policy.max_txs_per_hour");
  }
  if (liveTokenRecordSize !== TOKEN_SPEND_RECORD_SIZE) {
    diffs.push(
      `TOKEN_SPEND_RECORD_SIZE: generated=${TOKEN_SPEND_RECORD_SIZE}, live=${liveTokenRecordSize}`,
    );
  }
  // Compare full prefix list — same names + offsets + sizes.
  if (liveFields.length !== VAULT_PREFIX_FIELDS.length) {
    diffs.push(
      `VAULT_PREFIX_FIELDS length: generated=${VAULT_PREFIX_FIELDS.length}, live=${liveFields.length}`,
    );
  } else {
    for (let i = 0; i < liveFields.length; i++) {
      const live = liveFields[i]!;
      const gen = VAULT_PREFIX_FIELDS[i]!;
      if (live.name !== gen.name || live.offset !== gen.offset || live.size !== gen.size) {
        diffs.push(
          `VAULT_PREFIX_FIELDS[${i}]: generated=${JSON.stringify(gen)}, live=${JSON.stringify(live)}`,
        );
      }
    }
  }

  if (diffs.length > 0) throw new VaultLayoutDriftError(diffs);
  log.debug(
    { audit: "MCP-311", fields: liveFields.length },
    "vault-layout-drift: generated artifact matches live IDL",
  );
}
