// AUTO-GENERATED — DO NOT EDIT.
//
// Generated by `mcp-server/scripts/gen-vault-layout.ts` from
// `sdk/idl/src/idl/agent_vault.json`. Run `npm run gen:vault-layout`
// (or `npm run build` which calls it via prebuild) after any change to
// the on-chain Vault struct.
//
// CI verifies `git diff --exit-code` for this file post-codegen so a
// Rust struct reorder surfaces as a CI failure rather than a runtime
// garbage decode (MCP-313).

export const VAULT_DISCRIMINATOR_SIZE = 8;
export const SPENT_TODAY_OFFSET = 73;
export const LAST_SPEND_DAY_OFFSET = 81;
export const POLICY_PER_TX_LIMIT_OFFSET = 89;
export const DAILY_LIMIT_OFFSET = 97;
export const POLICY_FIXED_END_OFFSET = 109;
export const TOKEN_SPEND_RECORD_SIZE = 64;

/**
 * Field offsets walked from the IDL at codegen time. The runtime drift
 * assertion (`vault-layout.ts`) re-walks the IDL and asserts these
 * constants still match — protects against the codegen artifact drifting
 * from the on-chain struct (MCP-311).
 */
export const VAULT_PREFIX_FIELDS: ReadonlyArray<{
  readonly name: string;
  readonly offset: number;
  readonly size: number;
}> = [
  {
    "name": "agent_identity",
    "offset": 8,
    "size": 32
  },
  {
    "name": "authority",
    "offset": 40,
    "size": 32
  },
  {
    "name": "paused",
    "offset": 72,
    "size": 1
  },
  {
    "name": "spent_today_lamports",
    "offset": 73,
    "size": 8
  },
  {
    "name": "last_spend_day",
    "offset": 81,
    "size": 8
  },
  {
    "name": "policy",
    "offset": 89,
    "size": 20
  },
  {
    "name": "policy.per_tx_limit_lamports",
    "offset": 89,
    "size": 8
  },
  {
    "name": "policy.daily_limit_lamports",
    "offset": 97,
    "size": 8
  },
  {
    "name": "policy.max_txs_per_hour",
    "offset": 105,
    "size": 4
  }
] as const;
