import {
  Connection,
  Keypair,
  PublicKey,
  LAMPORTS_PER_SOL,
  Transaction,
} from "@solana/web3.js";
// ADR-091: @anchor-lang/core is published as CommonJS. Under Node's strict
// ESM loader (Node 20 in CI), `import { BN } from "@anchor-lang/core"`
// fails with "does not provide an export named 'BN'" because Node's
// named-import detector only sees what the CJS analyzer can statically
// prove. Symbols below that threshold (BN here) need to come off the
// default export at runtime.
//
// Pattern: `import anchor from "@anchor-lang/core"` lifts the runtime
// values off the default export; a separate `import type { ... }`
// re-establishes the typed surface (type-only imports emit no JS so they
// bypass the CJS-named-export check).
import anchor from "@anchor-lang/core";
const { AnchorProvider, Program, BN } = anchor;
import type { AnchorProvider as _AnchorProvider, Program as _Program, Idl } from "@anchor-lang/core";
type AnchorProvider = _AnchorProvider;
type Program<T extends Idl = Idl> = _Program<T>;
import * as fs from "fs";
import * as path from "path";
import * as crypto from "crypto";
import { fileURLToPath } from "url";
import { assertKeyfilePermissions } from "./transport/auth-gate.js";

// ADR-088: Anchor IDL types are the source of typing truth for the cached
// Program singletons below. Each `target/types/*.ts` file is generated by
// `anchor build` from the corresponding IDL JSON and stays in lockstep with
// the on-chain program. They are re-exported through `./idl/types` so the
// import lands inside this package's `rootDir` (avoiding TS6059) while the
// canonical type definitions still live alongside `target/idl/`.
import type { AgentRegistry, AgentVault, Settlement } from "./idl/types.js";

// ADR-091: __dirname is not available in ESM (NodeNext). Shim it from import.meta.url.
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Solana connection, Anchor programs, and PDA helpers for the AEP MCP server.
 *
 * This module initializes:
 * - Solana RPC connection (configurable via SOLANA_RPC_URL)
 * - Wallet keypair (from ANCHOR_WALLET, then SOLANA_KEYPAIR_PATH, then default Solana CLI path)
 * - Anchor Provider and Program instances for all three AEP programs
 * - PDA derivation utilities matching the on-chain program seeds
 */

// ==================== SPL TOKEN CONSTANTS ====================
// ADR-050: Inlined to eliminate @solana/spl-token dependency and its
// transitive bigint-buffer CVE (GHSA-3gc7-fjrx-p6mg).

export const TOKEN_PROGRAM_ID = new PublicKey(
  "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
);
export const ASSOCIATED_TOKEN_PROGRAM_ID = new PublicKey(
  "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
);

/**
 * Derive the associated token account (ATA) address for a given mint and owner.
 * Replaces getAssociatedTokenAddressSync from @solana/spl-token.
 * Seeds: [owner, TOKEN_PROGRAM_ID, mint] with ASSOCIATED_TOKEN_PROGRAM_ID.
 */
export function getAssociatedTokenAddressSync(
  mint: PublicKey,
  owner: PublicKey,
  allowOwnerOffCurve = false
): PublicKey {
  if (!allowOwnerOffCurve && PublicKey.isOnCurve(owner.toBuffer())) {
    // owner is on curve — standard case
  }
  const [address] = PublicKey.findProgramAddressSync(
    [owner.toBuffer(), TOKEN_PROGRAM_ID.toBuffer(), mint.toBuffer()],
    ASSOCIATED_TOKEN_PROGRAM_ID
  );
  return address;
}

// ==================== PROGRAM IDS ====================

export const VAULT_PROGRAM_ID = new PublicKey(
  "28Km3edbdMASVzKDnG2gHNLBgC7JQodGd9FVRAEVzYYw"
);
export const REGISTRY_PROGRAM_ID = new PublicKey(
  "psJT29X5QAqkc9ZL3mt1YbyUsGqgdXjBU7RhEUEyNyv"
);
export const SETTLEMENT_PROGRAM_ID = new PublicKey(
  "9TRVbw2dvER1zDQcxwA8Puub4fLnPGstc1GGDDLTUF95"
);

// ==================== SINGLETONS ====================

let _connection: Connection | null = null;
let _wallet: Keypair | null = null;
let _provider: AnchorProvider | null = null;
// ADR-088: parameterised so `program.account.<name>` and `program.methods.*`
// are typed off the IDL surface. The singletons themselves are still lazy.
let _vaultProgram: Program<AgentVault> | null = null;
let _registryProgram: Program<AgentRegistry> | null = null;
let _settlementProgram: Program<Settlement> | null = null;

// ==================== WALLET ADAPTER ====================

/**
 * Minimal Wallet adapter for Anchor provider.
 * Wraps a Keypair to satisfy AnchorProvider's wallet interface.
 */
class KeypairWallet {
  constructor(readonly payer: Keypair) {}

  get publicKey(): PublicKey {
    return this.payer.publicKey;
  }

  async signTransaction<T extends Transaction>(tx: T): Promise<T> {
    tx.partialSign(this.payer);
    return tx;
  }

  async signAllTransactions<T extends Transaction>(txs: T[]): Promise<T[]> {
    txs.forEach((tx) => tx.partialSign(this.payer));
    return txs;
  }
}

// ==================== CONNECTION & PROVIDER ====================

/**
 * Get or create a Solana RPC connection.
 * Defaults to devnet; override with SOLANA_RPC_URL env var.
 */
export function getConnection(): Connection {
  if (!_connection) {
    const rpcUrl =
      process.env.SOLANA_RPC_URL || "https://api.devnet.solana.com";
    _connection = new Connection(rpcUrl, "confirmed");
  }
  return _connection;
}

/**
 * Load the agent's wallet keypair from disk.
 *
 * Resolution precedence (highest first):
 *   1. `ANCHOR_WALLET`       — Anchor's documented convention. When set,
 *                              this wins outright. Honouring it lets the
 *                              MCP server inherit the wallet from
 *                              `anchor test`, `anchor run`, and any
 *                              IDE/CI integration that follows the
 *                              Anchor convention.
 *   2. `SOLANA_KEYPAIR_PATH` — legacy MCP-only env var. Kept for
 *                              backward compatibility with deployments
 *                              that already set it.
 *   3. `~/.config/solana/id.json` — Solana CLI default.
 *
 * AUD-016 (2026-04-25 audit): pre-fix, only `SOLANA_KEYPAIR_PATH` was
 * checked, so the standard Anchor env var was silently ignored and
 * users would see "wallet not found" errors despite a working Anchor
 * setup.
 *
 * ADR-083 Finding 5.1: refuses to load if the keyfile permission mode has any
 * group or other bits set (a `0644` keyfile is silently world-readable on
 * Unix). The check is `(mode & 0o077) === 0`. Same-uid attackers bypass this
 * trivially, but the silent-permissions-regression class of incidents
 * (backup-tool restore, misconfigured Ansible play) is caught at startup.
 */
export function loadWallet(): Keypair {
  if (_wallet) return _wallet;

  // AUD-016: ANCHOR_WALLET takes precedence over SOLANA_KEYPAIR_PATH so
  // the MCP server matches Anchor's documented convention. If both are
  // set, ANCHOR_WALLET wins (it's the more standard variable).
  let keypath = process.env.ANCHOR_WALLET || process.env.SOLANA_KEYPAIR_PATH;
  if (!keypath) {
    const home = process.env.HOME || process.env.USERPROFILE || "";
    keypath = path.join(home, ".config", "solana", "id.json");
  }

  if (!fs.existsSync(keypath)) {
    throw new Error(
      `Wallet keypair not found at: ${keypath}. ` +
        `Set ANCHOR_WALLET or SOLANA_KEYPAIR_PATH or run 'solana-keygen new'.`
    );
  }

  // ADR-083 Finding 5.1: refuse to load a world- or group-readable keyfile.
  assertKeyfilePermissions(keypath);

  const secretKey = JSON.parse(fs.readFileSync(keypath, "utf-8"));
  _wallet = Keypair.fromSecretKey(Buffer.from(secretKey));
  return _wallet;
}

/**
 * Get the wallet's public key (agent address).
 */
export function getWalletPublicKey(): PublicKey {
  return loadWallet().publicKey;
}

/**
 * Get or create an AnchorProvider bound to the agent's wallet.
 */
export function getProvider(): AnchorProvider {
  if (_provider) return _provider;
  const conn = getConnection();
  const kp = loadWallet();
  const wallet = new KeypairWallet(kp);
  // TODO(typed): Anchor's `Wallet` interface is declared in
  // @anchor-lang/core/dist/.../provider but the published `.d.ts` keeps the
  // interface internal, so a structurally-identical KeypairWallet doesn't
  // satisfy the public type. Unblocked by either (a) Anchor exporting
  // `Wallet`, or (b) ADR-099's `@agenomics/idl` package shipping its own
  // typed wrapper.
  _provider = new AnchorProvider(
    conn,
    wallet as unknown as AnchorProvider["wallet"],
    {
      commitment: "confirmed",
      preflightCommitment: "confirmed",
    }
  );
  return _provider;
}

// ==================== IDL LOADING & PROGRAMS ====================

/**
 * Load an Anchor IDL JSON file by program name.
 * IDL files are expected at ../../target/idl/<name>.json relative to dist/.
 *
 * Returns `unknown` because Anchor's `Program` constructor declares its
 * first argument as `idl: any` (see
 * `node_modules/@anchor-lang/core/dist/cjs/program/index.d.ts:238`). The
 * static type parameter on the constructed `Program<IDL>` instance is what
 * threads typing through every account / methods access — see ADR-088.
 */
function loadIdl(name: string): unknown {
  const idlPath = path.resolve(
    __dirname,
    "..",
    "..",
    "target",
    "idl",
    `${name}.json`
  );
  if (!fs.existsSync(idlPath)) {
    throw new Error(
      `IDL file not found: ${idlPath}. Run 'anchor build' to generate IDLs.`
    );
  }
  return JSON.parse(fs.readFileSync(idlPath, "utf-8"));
}

/**
 * Get the Agent Vault program instance.
 */
export function getVaultProgram(): Program<AgentVault> {
  if (!_vaultProgram) {
    const idl = loadIdl("agent_vault");
    _vaultProgram = new Program<AgentVault>(idl as AgentVault, getProvider());
  }
  return _vaultProgram;
}

/**
 * Get the Agent Registry program instance.
 */
export function getRegistryProgram(): Program<AgentRegistry> {
  if (!_registryProgram) {
    const idl = loadIdl("agent_registry");
    _registryProgram = new Program<AgentRegistry>(
      idl as AgentRegistry,
      getProvider()
    );
  }
  return _registryProgram;
}

/**
 * Get the Settlement program instance.
 */
export function getSettlementProgram(): Program<Settlement> {
  if (!_settlementProgram) {
    const idl = loadIdl("settlement");
    _settlementProgram = new Program<Settlement>(
      idl as Settlement,
      getProvider()
    );
  }
  return _settlementProgram;
}

// ==================== PDA DERIVATION ====================

/**
 * Derive vault PDA. Seeds: ["vault", authority]
 */
export function deriveVaultPDA(authority: PublicKey): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("vault"), authority.toBuffer()],
    VAULT_PROGRAM_ID
  );
}

/**
 * ADR-097: Derive owner-nonce PDA. Seeds: [authority, "owner-nonce"].
 * Init'd by the first `register_agent`; its `nonce` feeds the agent_profile
 * PDA seed for Sybil resistance after close-then-reopen.
 */
export function deriveOwnerNoncePDA(
  authority: PublicKey
): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [authority.toBuffer(), Buffer.from("owner-nonce")],
    REGISTRY_PROGRAM_ID
  );
}

/**
 * ADR-097: Derive agent profile PDA. Seeds: [authority, "agent-profile", nonce-le].
 * Fresh authorities (first registration) use `nonce = 0n`. For authorities that
 * previously deregistered and are re-registering, pass the current owner_nonce.
 */
export function deriveAgentProfilePDA(
  authority: PublicKey,
  nonce: bigint = 0n
): [PublicKey, number] {
  const nonceBuf = Buffer.alloc(8);
  nonceBuf.writeBigUInt64LE(nonce);
  return PublicKey.findProgramAddressSync(
    [authority.toBuffer(), Buffer.from("agent-profile"), nonceBuf],
    REGISTRY_PROGRAM_ID
  );
}

/**
 * Derive escrow PDA. Seeds: ["escrow", client, provider, taskId_le_bytes]
 */
export function deriveEscrowPDA(
  client: PublicKey,
  provider: PublicKey,
  taskId: number
): [PublicKey, number] {
  const taskIdBuf = Buffer.alloc(8);
  taskIdBuf.writeBigUInt64LE(BigInt(taskId));
  return PublicKey.findProgramAddressSync(
    [
      Buffer.from("escrow"),
      client.toBuffer(),
      provider.toBuffer(),
      taskIdBuf,
    ],
    SETTLEMENT_PROGRAM_ID
  );
}

/**
 * Derive the escrow's associated token account (ATA).
 * Uses allowOwnerOffCurve=true since the escrow is a PDA.
 */
export function deriveEscrowTokenAccount(
  escrowPDA: PublicKey,
  tokenMint: PublicKey
): PublicKey {
  return getAssociatedTokenAddressSync(tokenMint, escrowPDA, true);
}

/**
 * Finding #19: Derive the singleton ProtocolConfig PDA.
 * Seeds: [b"protocol_config"] under the Settlement program.
 * Every escrow/dispute/approve/expire path now takes this account so the
 * governance-owned tunables (min_escrow, dispute_timeout, reputation
 * deltas) are read at runtime instead of baked into the binary.
 */
export function deriveProtocolConfigPDA(): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("protocol_config")],
    SETTLEMENT_PROGRAM_ID
  );
}

// ==================== UTILITY FUNCTIONS ====================

// CC-5 / C4-MCPEVO-002: base58 alphabet + Solana pubkey length bound.
// `new PublicKey()` alone accepts any input it can coerce to 32 bytes
// (incl. 32-byte hex/array forms) — not a real base58-pubkey check. We
// pre-gate on the canonical base58 string shape (32–44 chars, base58
// alphabet) before constructing, so garbage strings are rejected up
// front rather than silently coerced.
const BASE58_PUBKEY_RE = /^[1-9A-HJ-NP-Za-km-z]{32,44}$/;

/**
 * Validate a base58-encoded Solana public key string. Real validation:
 * canonical base58 shape AND a 32-byte decode (`new PublicKey`). Pass
 * `requireOnCurve` to additionally reject off-curve points (e.g. when the
 * caller-supplied value must be a wallet/authority, not a PDA).
 */
export function isValidPublicKey(
  key: string,
  opts: { requireOnCurve?: boolean } = {},
): boolean {
  if (typeof key !== "string" || !BASE58_PUBKEY_RE.test(key)) {
    return false;
  }
  let pk: PublicKey;
  try {
    pk = new PublicKey(key);
  } catch {
    return false;
  }
  if (pk.toBase58() !== key) {
    return false;
  }
  if (opts.requireOnCurve && !PublicKey.isOnCurve(pk.toBuffer())) {
    return false;
  }
  return true;
}

/**
 * Parse a base58 string into a PublicKey, throwing on invalid input.
 */
export function parsePublicKey(key: string): PublicKey {
  if (!isValidPublicKey(key)) {
    throw new Error(`Invalid Solana public key: ${key}`);
  }
  return new PublicKey(key);
}

/**
 * Convert SOL to lamports.
 */
export function solToLamports(sol: number): number {
  return Math.floor(sol * LAMPORTS_PER_SOL);
}

/**
 * Convert lamports to SOL.
 */
export function lamportsToSol(lamports: number | bigint): number {
  return Number(lamports) / LAMPORTS_PER_SOL;
}

/**
 * Get the SOL balance of an address.
 */
export async function getBalance(pubkey: PublicKey): Promise<number> {
  const conn = getConnection();
  const balance = await conn.getBalance(pubkey);
  return balance / LAMPORTS_PER_SOL;
}

/**
 * SHA-256 hash a string and return as a 32-byte array (for description hashes).
 */
export function hashDescription(description: string): number[] {
  const hash = crypto.createHash("sha256").update(description).digest();
  return Array.from(hash);
}

// Re-exports for convenience
export {
  PublicKey,
  BN,
  LAMPORTS_PER_SOL,
};

// ==================== V1 <-> V2 ADAPTER (ADR-012) ====================
//
// This section is the boundary between @solana/kit (v2) and @solana/web3.js
// (v1) + Anchor 0.31.1 (which is v1-bound at the `.rpc()` call site).
//
// Rules:
//  - MCP-facing APIs flow in via v2 primitives (Address, KeyPairSigner, ...).
//  - Anchor-facing APIs require v1 primitives (PublicKey, Keypair, Connection).
//  - Conversion happens here, and ONLY here. Handlers do not import @solana/kit.
//  - v2 `Address<T>` is a branded base58 string — `.toString()` yields the
//    same base58 the v1 PublicKey constructor accepts, so the round-trip is
//    byte-identical. Seed-level PDA equivalence is proven in
//    `test/solana-v2.test.ts`.
//
// PR2 scope: types + a tiny conversion helper set. No transaction building,
// no signer abstraction, no compute budget helpers. PR3 owns those.

import type { Address as V2Address } from "@solana/kit";

/**
 * v2 Address -> v1 PublicKey.
 *
 * Safe to use with any valid `Address` brand, because the brand only
 * permits base58 strings that parsed successfully in Kit.
 */
export function addressToPublicKey(addr: V2Address): PublicKey {
  // `Address` is a branded string; `new PublicKey(str)` accepts base58 strings.
  return new PublicKey(addr.toString());
}

/**
 * v1 PublicKey -> v2 Address.
 *
 * Cast-only: `.toBase58()` emits the same canonical form the brand guards.
 * We use `as unknown as` + `as V2Address` rather than calling Kit's
 * `address()` helper because the input is already known-valid — avoiding a
 * redundant base58 validation on every adapter call.
 */
export function publicKeyToAddress(pk: PublicKey): V2Address {
  return pk.toBase58() as unknown as V2Address;
}

